### ISSUE TITLE
Problem with bootstrap's collapse sidebar

### ISSUE THREAD

**Issue by nattaponx** [anysom/GridColumnCarousel#4]
Hi there,

I am using your valuable grid column carousel and I am facing a problem right now. I use it in a bootstrap here

 http://themewagon.com/themes/adminlte-free-bootstrap-3-html5-admin-panel-template/ 

When the sidebar is collapsed, grid columns in carousel don't fit the content class width where I put it. Let say I have 2 columns per slide and I have 2 slides. When sidebar is collapsed, the size of all columns remain the same and that makes the other column in the second slide overlap on first slide.

Any suggestion to this would be appreciated.
![aaa](https://cloud.githubusercontent.com/assets/10026349/8755750/8ab09fda-2ccd-11e5-9a6f-7aabd21b2987.png)
![bbb](https://cloud.githubusercontent.com/assets/10026349/8755751/8ab10556-2ccd-11e5-96e7-feec8d2d3e11.png)

**Comment by anysom** [comment]
Hi there nattaponx..

I am on vacation right now and haven't got my computer with me. Just my phone.. But I will look it to this as soon as I get home. In about a weeks time.

So as of now the carousel only reacts to viewport size changes, not container size changes. So I will see what solution I come up with.

Cheers

**Comment by anysom** [comment]
Hi Nattaponx

I have added the function 'startWatchManualResize' to the GCCarousel you can call when you open the menu. Normally the carousel only reacts to window resize events, so this is a manual way to tell the carousel to watch for resizing.

When the menu is done opening you can 'endWatchManualResize' to stop it from keeping to resize it self and use resources. OR you can pass a number variable to the start method to tell it for how long it should watch for resizing..

I will update the documentation on the page in the comming days, but i just wanted to let you know that the issue is fixed and the code is out.. You can watch my example in the index.html which is the test page..

Cheers! :)

**Comment by nattaponx** [comment]
Thank you!! You're awesome. I will look into the code.
