### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by serdarkok** [anysom/GridColumnCarousel#5]
Hi, 
Sorry my English.

Thanks, good job. How can i add swipe mode, touchable slide.

Thanks.

**Comment by anysom** [comment]
Hey Serdakok

I haven't implemented any touch functionality yet and it wasn't in my pipeline because I don't want my carousel to be dependant upon any swipe libraries.. 

However, I'll look into this a bit in the weekend and see if I can find a quick solution for you. I will keep you updated :)

Cheers

**Comment by serdarkok** [comment]
Thank you very much for answer. It's very urgent for me. I will wait your solution.

**Comment by anysom** [comment]
Hi again.

Just writing to let you know that I did not come up with a solution in the weekend, and this week I will be too busy at work to be working on it. But feel free to look into a solution and send me a pull request :)
